### ISSUE TITLE
Cannot run prepareData.py successfully

### ISSUE THREAD

**Issue by RoyMikeJiang** [neeharperi/DeepKNNDefense#1]
![issue_1](https://user-images.githubusercontent.com/53047899/111935971-9a014480-8aff-11eb-8acd-df2a878e0702.png)

**Comment by neeharperi** [comment]
Make sure you stitch together all of the modelCheckPoint0X tar partitions together in a folder called modelCheckPoints. Once you have done this, delete any of the newly generated folders and re-run prepareData.py, and it should work correctly.  If you can't get that to work, just download it directly from the following [link](https://drive.google.com/drive/folders/17yBI8Kqk6BmeA5PTaee-badlkincw2g1?usp=sharing)

**Comment by neeharperi** [comment]
Make sure you stitch together all of the modelCheckPoint0X tar partitions together in a folder called modelCheckPoints. Once you have done this, delete any of the newly generated folders and re-run prepareData.py, and it should work correctly.  If you can't get that to work, just download it directly from the following [link](url)

**Comment by RoyMikeJiang** [comment]
thanks!

**Comment by RoyMikeJiang** [comment]
Thanks again for your answer at first.
But, after added these files in the link, i shows another problem.
![image](https://user-images.githubusercontent.com/53047899/111983119-bd021780-8b44-11eb-958d-b4b56d5453e5.png)
The line 52.
![image](https://user-images.githubusercontent.com/53047899/111983187-d4410500-8b44-11eb-9ac9-b17402c7daeb.png)
![image](https://user-images.githubusercontent.com/53047899/111983602-487ba880-8b45-11eb-92e7-62884f442a62.png)
![image](https://user-images.githubusercontent.com/53047899/111983626-4f0a2000-8b45-11eb-9286-0047aaa5c693.png)
![image](https://user-images.githubusercontent.com/53047899/111983654-55989780-8b45-11eb-8894-87779523c7e7.png)
![image](https://user-images.githubusercontent.com/53047899/111983679-5c270f00-8b45-11eb-8586-fb5dd691c241.png)
![image](https://user-images.githubusercontent.com/53047899/111983710-647f4a00-8b45-11eb-840a-42f79c47ce68.png)
![image](https://user-images.githubusercontent.com/53047899/111983747-6cd78500-8b45-11eb-9bb6-950020319dc5.png)
![image](https://user-images.githubusercontent.com/53047899/111983781-77921a00-8b45-11eb-9fbe-b8e064c4ff64.png)
Every model shows this problem above, it seems that the files added are not suit for this project.

This is my version of torch.
![image](https://user-images.githubusercontent.com/53047899/111983882-9a243300-8b45-11eb-91ce-7242331c492f.png)

**Comment by neeharperi** [comment]
I'm guessing that you are either running this on your CPU or a single GPU, so the loading error you are getting is because I wrote this code on a multi-GPU machine and the checkpoints are saved with nn.DataParallel. You can refactor the checkpoint to remove DataParallel as described by [this](https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686/4) forum. Hope this helps!

**Comment by RoyMikeJiang** [comment]
After using two NVIDIA Tesla K80 to run the extractFeatures.py, it still shows the same error.
![OGEUSL_XF%L1 $H0P`HF%XT](https://user-images.githubusercontent.com/53047899/117256663-89254c00-ae7d-11eb-9dd5-f70ecdf46939.png)

**Comment by neeharperi** [comment]
There is no key "net" in CheckPoint. Verify to see what keys you have in there to make sure you didn't rename it, or drop it.

**Comment by RoyMikeJiang** [comment]
Hi!
I found what the problem is. The files in the Google Drive may be not correct. After unpacking the original files (modelCheckPointPartition0x) in the project, it works well.

**Comment by ZHL45** [comment]
> After using two NVIDIA Tesla K80 to run the extractFeatures.py, it still shows the same error. ![OGEUSL_XF%L1 $H0P`HF%XT](https://user-images.githubusercontent.com/53047899/117256663-89254c00-ae7d-11eb-9dd5-f70ecdf46939.png)

I would be appriciated it if you could share this part of code with me.
