### ISSUE TITLE
Question about comparison picture in the article.

### ISSUE THREAD

**Issue by RoyMikeJiang** [neeharperi/DeepKNNDefense#2]
![image](https://user-images.githubusercontent.com/53047899/133970713-01970d8a-ab72-4efd-ad97-ea1c5a0ab8bd.png)
Sorry for bothering again. After reading the article, I wonder to know how you get the Defense Success Rate and Classification Accuracy about the other defenses. Is there any code or article about them?
Thanks!

**Comment by neeharperi** [comment]
We implemented this using either sklearn or off-the-shelf methods. I can't seem to find the original code for this, but it should be straightforward to reimplement these simple baselines. The proposed KNN defense is implemented in the data loader. You can probably do something similar for the other methods (Definitions of these methods are on pg 6-7). Note that adversarial defense is not a filtering-based method, and should be implemented differently.
